config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'

  draw(:api)

  devise_for :users, controllers: {
    sessions:           'users/sessions',
    registrations:      'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations:      'users/confirmations'
  }

  resources :users do
    member do
      get   :chat
      patch :change_status
    end
  end
  get 'search_users', to: 'users#search'

  get 'dms', to: 'rooms#dms'

  resources :rooms do
    collection do
      get :all
    end

    resources :messages, only: %i[create destroy]

    resources :participants, only: %i[create destroy] do
      member do
        post   :block
        post   :unblock
        post   :change_role
        post   :join
        patch  :toggle_notifications
        delete :leave
      end
    end
  end

  resources :messages, only: [] do
    resources :reactions, only: %i[create]
    delete 'reactions', to: 'reactions#destroy'
  end

  resources :favorites, only: [] do
    post :toggle, on: :collection
  end

  resources :contacts, only: %i[index create update destroy] do
    collection do
      get  :requests
      post :accept_all
    end
    delete :delete, on: :member
  end

  resources :notifications, only: %i[index] do
    patch :mark_as_read, on: :member
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/views/search/_form.html.erb
<%= form_with url: search_users_path, method: :get, data: { turbo_frame: 'search_results' }, class: 'd-flex gap-2 mb-3', role: 'search' do %>
  <%= label_tag 'q[search]', 'Search Users' %>
  <%= search_field_tag 'q[search]', params.dig(:q, :search), class: 'form-control me-2', autocomplete: 'off', placeholder: 'Enter name, email, or username' %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/search/_search_modal.html.erb
<div class="search-modal modal" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="search-modal-dialog modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="searchModalLabel">
          Search Results
          <span data-bs-toggle="tooltip"
                data-bs-placement="top"
                data-bs-custom-class="custom-tooltip"
                data-bs-title="Use symbols before your search: #username, @email, $name"
                data-controller="bs-init-component" data-action="bs-init-component#bs_init">
          <i class="bi bi-question-circle"></i>
        </span></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body mb-2">
        <%= render partial: 'search/form' %>
        <turbo-frame id="search_results">
          <%= render 'search/search_results', search_results: defined?(@search_results) ? @search_results : {} %>
        </turbo-frame>
      </div>
    </div>
  </div>
</div>

app/views/search/_search_results.html.erb
<turbo-frame id="search_results">
  <ul class="list-group">
    <% search_results.each do |user| %>
      <li class="list-group-item list-group-item-action px-1">
        <%= render partial: 'rooms/room_info/room_info_user', locals: { user: user } %>
      </li>
    <% end %>
  </ul>
</turbo-frame>