config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'

  draw(:api)

  devise_for :users, controllers: {
    sessions:           'users/sessions',
    registrations:      'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations:      'users/confirmations'
  }

  resources :users do
    member do
      get   :chat
      patch :change_status
    end
  end
  get 'search_users', to: 'users#search'

  get 'dms', to: 'rooms#dms'

  resources :rooms do
    collection do
      get :all
    end

    resources :messages, only: %i[create destroy]

    resources :participants, only: %i[create destroy] do
      member do
        post   :block
        post   :unblock
        post   :change_role
        post   :join
        patch  :toggle_notifications
        delete :leave
      end
    end
  end

  resources :messages, only: [] do
    resources :reactions, only: %i[create]
    delete 'reactions', to: 'reactions#destroy'
  end

  resources :favorites, only: [] do
    post :toggle, on: :collection
  end

  resources :contacts, only: %i[index create update destroy] do
    collection do
      get  :requests
      post :accept_all
    end
    delete :delete, on: :member
  end

  resources :notifications, only: %i[index] do
    patch :mark_as_read, on: :member
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/models/notification.rb
# frozen_string_literal: true

class Notification < ApplicationRecord
  belongs_to :item, polymorphic: true
  belongs_to :receiver, class_name: 'User'
  belongs_to :sender, class_name: 'User'

  scope :unviewed, -> { where(viewed: false) }
end

app/controllers/api/v1/notifications/mark_as_read/authorizer.rb
# frozen_string_literal: true

module Api
  module V1
    module Notifications
      module MarkAsRead
        # Authorizes a participant to change role
        class Authorizer
          # Authorizes a participant to change role
          #
          # @param current_user [User] current logged user
          # @param notification [Notification] notification instance
          # @return [Notification] notification record if authorized, raises Pundit::NotAuthorizedError otherwise
          def call(current_user, notification)
            Pundit.authorize current_user, notification, :mark_as_read?, policy_class: UserNotificationPolicy
          end
        end
      end
    end
  end
end

app/controllers/api/v1/notifications/mark_as_read/serializer.rb
# frozen_string_literal: true

module Api
  module V1
    module Notifications
      module MarkAsRead
        # Serializes a Notification instance into a hash
        class Serializer
          # Serialize a notification record
          #
          # @param record [Notification] notification instance to be serialized
          # @return [Hash] serialized notification attributes
          def call(record)
            Api::V1::Serializers::NotificationsSerializer.new(record).serializable_hash
          end
        end
      end
    end
  end
end

app/controllers/api/v1/notifications/mark_as_read/transaction.rb
# frozen_string_literal: true

module Api
  module V1
    module Notifications
      module MarkAsRead
        # Orchestrates notification#mark_as_read action
        class Transaction
          include ::TransactionResponse
          # Orchestrates notification#mark_as_read action
          #
          # @param current_user [User] current logged user
          # @param notification [Notification] notification instance
          # @return [Hash] transaction response with status, data, message
          def call(current_user, notification)
            Authorizer.new.call(current_user, notification)
            Validator.new.call

            result = ::Notifications::MarkAsReadService.new(notification, current_user).call

            raise Errors::ServiceError, [result.data, result.error_code] unless result.success?

            response(status: :ok, data: Serializer.new.call(result.data), message: 'Role changed')
          end
        end
      end
    end
  end
end

app/controllers/api/v1/notifications/mark_as_read/validator.rb
# frozen_string_literal: true

module Api
  module V1
    module Notifications
      module MarkAsRead
        # Validates params for marking a notification as read
        class Validator
          # Validates params for marking a notification as read, currently does nothing
          #
          # @return [Boolean] true, always
          def call
            true
          end
        end
      end
    end
  end
end

app/controllers/api/v1/notifications_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class NotificationsController < BaseController
      before_action :set_notification, only: %i[mark_as_read]

      def index
        render json: Serializers::NotificationsSerializer.new(current_user.notifications).serializable_hash
      end

      def mark_as_read
        render_response(Api::V1::Notifications::MarkAsRead::Transaction.new.call(current_user, @notification))
      end

      private

      def set_notification
        @notification = current_user.notifications.find(params[:id])
      end
    end
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications
    @notifications.update(viewed: true)
  end

  def mark_as_read # rubocop:disable Metrics/MethodLength
    @notification = current_user.notifications.find(params[:id])
    result = Notifications::MarkAsReadService.new(@notification, current_user).call

    respond_to do |format|
      format.turbo_stream
      format.html do
        if result.success?
          redirect_to notifications_path
        else
          redirect_to notifications_path, alert: 'Could not mark notification as read'
        end
      end
    end
  end
end

app/views/notifications/_count.html.erb
<% if count.positive? %>
  <span class="notifications-badge position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
          <%= count %>
    <span class="visually-hidden">unread messages</span>
  </span>
<% end %>

app/views/notifications/_fixed_notification.html.erb
<%= content_tag :div, id: "notification_#{notification.id}",
                class: 'notification d-flex align-items-center' do %>
  <div class="toast-container position-fixed top-0 end-0 p-3">
    <div class="toast show" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong class="me-auto"><%= notification.notification_type.humanize %></strong>
        <small><%= time_ago_in_words(notification.created_at) %></small>
        <%= button_to mark_as_read_notification_path(notification),
                      method: :patch,
                      remote: true,
                      class: 'btn close',
                      data: { turbo_stream: true } do %>
          <span aria-hidden="true">&times;</span>
        <% end %>
      </div>
      <div class="toast-body">
        <%= render "notifications/variants/#{notification.type.underscore}/#{notification.notification_type.underscore}",
                   notification: notification %>
      </div>
    </div>
  </div>
<% end %>

app/views/notifications/_notification.html.erb
<%= render "notifications/variants/#{notification.type.underscore}/#{notification.notification_type.underscore}",
           notification: notification %>

app/views/notifications/_notifications.html.erb
<h1>Notifications</h1>

<ul>
  <% @notifications.each do |notification| %>
    <li>
      <%= notification %>
    </li>
  <% end %>
</ul>

app/views/notifications/_user_joined.html.erb
<div class="room_notification">
  <strong><%= user.username %></strong> joined the room.
</div>

app/views/notifications/index.html.erb
<div class="container mt-5">
  <h4 class="mb-4 text-center">Your Notifications</h4>

  <% if @notifications.any? %>
    <ul class="list-unstyled d-flex flex-column gap-3 overflow-y-auto main-scroll-bar" style="max-height: 70vh;">
      <% @notifications.order(created_at: :desc).each do |notification| %>
        <% data_attrs = { turbo_frame: 'modal_frame', 'turbo-prefetch': false } if notification.item.instance_of?(User) %>
        <% notification_link = notification.item_type == 'User' ? notification.sender : notification.item %>

        <%= link_to notification_link, data: data_attrs, class: 'notification-item d-flex gap-3 p-3 rounded shadow-sm align-items-start text-decoration-none text-dark bg-light position-relative hover-shadow' do %>
          <% if notification.sender && notification.sender != notification.receiver %>
            <%= render partial: 'shared/default_avatar', locals: { user: notification.sender, size: 50, rounded: true } %>
          <% end %>
          <div class="flex-grow-1">
            <p class="fw-semibold mb-1 text-muted"><%= notification.notification_type.titleize %></p>
            <%= render notification, locals: { notification: notification } %>
            <small class="text-muted"><%= time_ago_in_words(notification.created_at) %> ago</small>
          </div>
          <span class="position-absolute top-0 end-0 mt-2 me-3 badge bg-secondary opacity-75"><%= notification.created_at.strftime('%b %-d') %></span>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <div class="alert alert-info text-center mt-5" role="alert">
      You have no notifications at the moment.
    </div>
  <% end %>
</div>

app/views/notifications/mark_as_read.turbo_stream.erb
<turbo-stream action="remove" target="notification_<%= @notification.id %>"></turbo-stream>
<turbo-stream action="replace" target="notifications_count">
  <%= @notification.receiver.unviewed_notifications_size %>
</turbo-stream>