config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  mount Sidekiq::Web => '/sidekiq'

  draw(:api)

  devise_for :users, controllers: {
    sessions:           'users/sessions',
    registrations:      'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    confirmations:      'users/confirmations'
  }

  resources :users do
    member do
      get   :chat
      patch :change_status
    end
  end
  get 'search_users', to: 'users#search'

  get 'dms', to: 'rooms#dms'

  resources :rooms do
    collection do
      get :all
    end

    resources :messages, only: %i[create destroy]

    resources :participants, only: %i[create destroy] do
      member do
        post   :block
        post   :unblock
        post   :change_role
        post   :join
        patch  :toggle_notifications
        delete :leave
      end
    end
  end

  resources :messages, only: [] do
    resources :reactions, only: %i[create]
    delete 'reactions', to: 'reactions#destroy'
  end

  resources :favorites, only: [] do
    post :toggle, on: :collection
  end

  resources :contacts, only: %i[index create update destroy] do
    collection do
      get  :requests
      post :accept_all
    end
    delete :delete, on: :member
  end

  resources :notifications, only: %i[index] do
    patch :mark_as_read, on: :member
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/views/rooms/room_info/tabs/_about.html.erb
<div class="room-info-about">
  <% if room.peer_room? && other_user %>
    <% label_text = 'Room with' %>
  <% else %>
    <% label_text = 'Room name' %>
  <% end %>
  <ul class="list-group my-4 about-group">
    <%= render 'rooms/editable_field', room:, field: 'name', label_text:, value: define_room_name(room) %>
  </ul>
  <ul class="list-group about-group">
    <% unless room.self_room? %>
      <%= render 'rooms/editable_field',
                 room:,
                 field: 'topic',
                 label_text: 'Topic',
                 value: room.topic && room.topic.empty? ? 'Click edit to change topic' : room.topic %>
      <%= render 'rooms/editable_field',
                 room:,
                 field: 'description',
                 label_text: 'Description',
                 value: room.description && room.description.empty? ? 'Click edit to change description' : room.description %>
      <li class="list-group-item about-group-item list-group-item-action">
        <div class="w-100 d-flex justify-content-between">
          <div class="about-text text-start">
            <b class="about-label m-0 p-0"><%= room.peer_room? ? 'Initiated' : 'Created' %> by </b>
            <p class="about-room-name text-break m-0 p-0"><%= room.creator.username %> on <%= room.created_at.to_fs(:short) %></p>
          </div>
        </div>
      </li>
      <%= button_to leave_room_participant_path(room), method: :delete, class: 'list-group-item about-group-item list-group-item-action' do %>
        <div class="w-100 d-flex justify-content-between">
          <div class="about-text text-start">
            <p class="about-label about-label-leave danger-action-color m-0 p-0">Leave</p>
          </div>
        </div>
      <% end %>
    <% end %>
    <p class="text-muted text-start pt-2">Room ID: <%= room.id %></p>
  </ul>
</div>

app/views/rooms/room_info/tabs/_change_roles.html.erb
<div class="room-info-members">
  <ul class="members-list list-group mt-4 w-100 d-flex flex-column">
    <% room.participants.where.not(role: :owner).find_each do |participant| %>
      <% user = participant.user %>
      <%= render layout: 'rooms/room_info/room_info_user_with_actions', locals: { user:, room: } do %>
        <% if participant.member? %>
          <div class="d-flex gap-1">
            <%= form_with url: block_room_participant_path(room), method: :post, local: true do %>
              <%= hidden_field_tag :user_id, participant.user.id %>
              <%= hidden_field_tag :role, :blocked %>
              <%= hidden_field_tag :room_id, room.id %>
              <%= submit_tag 'Block', class: 'btn main-btn-remove btn-modal py-1 w-100' %>
            <% end %>

            <%= form_with url: change_role_room_participant_path(room), method: :post, local: true do %>
              <%= hidden_field_tag :user_id, participant.user.id %>
              <%= hidden_field_tag :role, :moderator %>
              <%= hidden_field_tag :room_id, room.id %>
              <%= submit_tag '+ Moderator', class: 'btn main-btn-add btn-modal py-1 w-100' %>
            <% end %>
          </div>
        <% elsif participant.blocked? %>
            <%= form_with url: unblock_room_participant_path(room), method: :post, local: true do %>
              <%= hidden_field_tag :user_id, participant.user.id %>
              <%= hidden_field_tag :role, :blocked %>
              <%= hidden_field_tag :room_id, room.id %>
              <%= submit_tag 'Unblock', class: 'btn main-btn-add btn-modal py-1 w-100' %>
            <% end %>
        <% else %>
          <div>
            <%= form_with url: change_role_room_participant_path(room), method: :post, local: true do %>
              <%= hidden_field_tag :user_id, participant.user.id %>
              <%= hidden_field_tag :role, :member %>
              <%= hidden_field_tag :room_id, room.id %>
              <%= submit_tag '- Moderator', class: 'btn main-btn-remove btn-modal py-1 w-100' %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/rooms/room_info/tabs/_members.html.erb
<div class="room-info-members">
  <ul class="members-list list-group mt-4 w-100 d-flex flex-column">
    <% if policy(room.find_participant(current_user)).create? %>
      <button type="button"
              class="btn p-0"
              data-controller="open-child-modal"
              data-action="click->open-child-modal#openTargetModal"
              data-bs-target="#contactsModal">
        <li class="members-list-item member-item list-group-item-action py-3 px-1 w-100 d-flex align-items-center gap-3">
            <div class="members-list-add message-avatar d-flex align-items-center">
              <div class="border d-flex justify-content-center align-items-center"
                   style="width: 40px; height: 40px">
                <i class="bi bi-person-add text-info"></i>
              </div>
            </div>
            <p class="fw-bold m-0">Add people</p>
        </li>
      </button>
    <% end %>
    <% room.participants.each do |participant| %>
      <% user = participant.user %>
      <%= render layout: 'rooms/room_info/room_info_user_with_actions', locals: { user:, room: } do %>
        <% if policy(room.find_participant(current_user)).destroy? && !(participant.owner? || participant.moderator?) %>
          <%= form_with url: room_participant_path(room), method: :delete, local: true do %>
            <%= hidden_field_tag :user_id, participant.user.id %>
            <%= submit_tag 'Remove', class: 'btn text-danger btn-modal py-1 w-100' %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </ul>
</div>